import "./globals.css";
import { Inter } from "next/font/google";
import { Lato } from 'next/font/google';

const inter = Inter({ subsets: ["latin"] });

const lato = Lato({
  subsets: ['latin', 'latin-ext'],
  weight: '400',
});
// local imports
// import SideBar from "./components/SideBar";

export const metadata = {
  title: "Tech Mart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lato.className}>
        {/* <SideBar /> */}
        {children}
      </body>
    </html>
  );
}
